import type { JiraConfig } from "../types/config.js";
import type { JiraIssue } from "../types/jira.js";
import { withRetry, fetchWithTimeout, RetryableError } from "../utils/retry.js";

export class JiraClient {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  private acceptanceCriteriaField: string;
  private readonly isCloud: boolean;
  private acFieldResolved = false;

  constructor(config: JiraConfig) {
    this.baseUrl = config.baseUrl.replace(/\/+$/, "");
    this.acceptanceCriteriaField =
      config.acceptanceCriteriaField ?? "";
    this.acFieldResolved = !!config.acceptanceCriteriaField;
    this.isCloud = config.type === "cloud" || (!config.type && config.baseUrl.includes("atlassian.net"));
    const authHeader = this.isCloud
      ? `Basic ${btoa(`${config.email}:${config.token}`)}`
      : `Bearer ${config.token}`;
    this.headers = {
      Authorization: authHeader,
      "Content-Type": "application/json",
      Accept: "application/json",
    };
  }

  private async resolveAcField(): Promise<string> {
    if (this.acFieldResolved && this.acceptanceCriteriaField) return this.acceptanceCriteriaField;
    if (this.acFieldResolved) return this.acceptanceCriteriaField;

    try {
      const apiVersion = this.isCloud ? "3" : "2";
      const url = `${this.baseUrl}/rest/api/${apiVersion}/field`;
      const response = await fetchWithTimeout(url, { headers: this.headers });
      if (response.ok) {
        const fields = (await response.json()) as Array<{ id: string; name: string; custom: boolean }>;
        const acField = fields.find(
          (f) => f.custom && /acceptance.?criteria/i.test(f.name),
        );
        if (acField) {
          this.acceptanceCriteriaField = acField.id;
          this.acFieldResolved = true;
          return acField.id;
        }
      }
    } catch {
      // fall through to default
    }

    this.acceptanceCriteriaField = "customfield_10035";
    this.acFieldResolved = true;
    return this.acceptanceCriteriaField;
  }

  async fetchIssue(issueKey: string): Promise<JiraIssue> {
    const acField = await this.resolveAcField();
    return withRetry(async () => {
      const fields = `summary,description,status,issuetype,labels,${acField}`;
      const apiVersion = this.isCloud ? "3" : "2";
      const url = `${this.baseUrl}/rest/api/${apiVersion}/issue/${issueKey}?fields=${fields}`;

      const response = await fetchWithTimeout(url, { headers: this.headers });

      if (!response.ok) {
        const body = await response.text();
        throw new RetryableError(
          `JIRA API error (${response.status}): ${body}`,
          response.status,
        );
      }

      const data = (await response.json()) as Record<string, unknown>;
      const fields_ = data.fields as Record<string, unknown>;

      return {
        key: data.key as string,
        fields: {
          summary: fields_.summary as string,
          description: this.extractText(fields_.description),
          acceptanceCriteria: this.extractText(
            fields_[this.acceptanceCriteriaField],
          ),
          status: fields_.status as { name: string },
          issuetype: fields_.issuetype as { name: string },
          labels: (fields_.labels as string[]) ?? [],
        },
      };
    });
  }

  async addComment(issueKey: string, body: string): Promise<void> {
    const apiVersion = this.isCloud ? "3" : "2";
    const url = `${this.baseUrl}/rest/api/${apiVersion}/issue/${issueKey}/comment`;

    await withRetry(async () => {
      const payload = this.isCloud
        ? { body: this.toAdf(body) }
        : { body };

      const response = await fetchWithTimeout(url, {
        method: "POST",
        headers: this.headers,
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const text = await response.text();
        throw new RetryableError(
          `JIRA API error (${response.status}): ${text}`,
          response.status,
        );
      }
    });
  }

  async hasIraACComment(issueKey: string): Promise<boolean> {
    const apiVersion = this.isCloud ? "3" : "2";
    const marker = "Generated by IRA";
    let startAt = 0;
    const maxResults = 50;

    try {
      while (true) {
        const url = `${this.baseUrl}/rest/api/${apiVersion}/issue/${issueKey}/comment?startAt=${startAt}&maxResults=${maxResults}`;
        const response = await fetchWithTimeout(url, { headers: this.headers });
        if (!response.ok) return false;

        const data = (await response.json()) as Record<string, unknown>;

        if (this.isCloud) {
          const comments = (data.comments ?? []) as Array<Record<string, unknown>>;
          if (comments.some((c) => {
            const body = c.body as Record<string, unknown> | undefined;
            if (!body || !Array.isArray(body.content)) return false;
            return JSON.stringify(body.content).includes(marker);
          })) return true;

          const total = typeof data.total === "number" ? data.total : comments.length;
          startAt += comments.length;
          if (startAt >= total || comments.length === 0) break;
        } else {
          const values = (data.values ?? data.comments ?? []) as Array<Record<string, unknown>>;
          if (values.some((c) => typeof c.body === "string" && c.body.includes(marker))) return true;

          const total = typeof data.total === "number" ? data.total : (typeof data.size === "number" ? data.size : values.length);
          startAt += values.length;
          if (startAt >= total || values.length === 0) break;
        }
      }
      return false;
    } catch {
      return false;
    }
  }

  async fetchEpicAndSubtasks(issueKey: string): Promise<{ epicSummary: string | null; subtasks: string[] }> {
    const apiVersion = this.isCloud ? "3" : "2";
    const url = `${this.baseUrl}/rest/api/${apiVersion}/issue/${issueKey}?fields=parent,subtasks`;

    try {
      const response = await fetchWithTimeout(url, { headers: this.headers });
      if (!response.ok) return { epicSummary: null, subtasks: [] };

      const data = (await response.json()) as Record<string, unknown>;
      const fields = data.fields as Record<string, unknown>;

      let epicSummary: string | null = null;
      const parent = fields.parent as Record<string, unknown> | undefined;
      if (parent) {
        const parentFields = parent.fields as Record<string, unknown> | undefined;
        if (parentFields) {
          const issueType = parentFields.issuetype as { name: string } | undefined;
          if (issueType?.name === "Epic") {
            epicSummary = parentFields.summary as string;
          }
        }
      }

      const subtaskList: string[] = [];
      const subtasks = fields.subtasks as Array<Record<string, unknown>> | undefined;
      if (subtasks) {
        for (const st of subtasks) {
          const stFields = st.fields as Record<string, unknown> | undefined;
          if (stFields) {
            subtaskList.push(`${st.key}: ${stFields.summary}`);
          }
        }
      }

      return { epicSummary, subtasks: subtaskList };
    } catch {
      return { epicSummary: null, subtasks: [] };
    }
  }

  private toAdf(body: string): Record<string, unknown> {
    const paragraphs = body.split(/\n{2,}/).map((block) => ({
      type: "paragraph",
      content: block.split("\n").flatMap((line, i) => [
        ...(i > 0 ? [{ type: "hardBreak" as const }] : []),
        { type: "text" as const, text: line },
      ]),
    }));

    return {
      type: "doc",
      version: 1,
      content: paragraphs,
    };
  }

  private extractText(field: unknown): string | null {
    if (typeof field === "string") return field;
    if (typeof field === "number") return String(field);
    if (!field || typeof field !== "object") return null;

    if (Array.isArray(field)) {
      const texts = field.map((v) => this.extractText(v)).filter(Boolean);
      return texts.length > 0 ? texts.join("\n") : null;
    }

    const node = field as Record<string, unknown>;

    // Leaf text node
    if (typeof node.text === "string") return node.text;

    // Recurse into ADF content arrays
    if (Array.isArray(node.content)) {
      const parts: string[] = [];
      for (const child of node.content) {
        const text = this.extractText(child);
        if (text) parts.push(text);
      }
      return parts.length > 0 ? parts.join(" ") : null;
    }

    return null;
  }
}
