import type { ReviewResult } from "../types/review.js";

export function buildSummary(result: ReviewResult): string {
  const lines: string[] = [];

  lines.push("# 🔍 IRA Review Summary");
  lines.push("");

  // Risk score
  if (result.risk) {
    const emoji =
      result.risk.level === "CRITICAL"
        ? "🔴"
        : result.risk.level === "HIGH"
          ? "🟠"
          : result.risk.level === "MEDIUM"
            ? "🟡"
            : "🟢";

    lines.push(
      `## ${emoji} Risk: ${result.risk.level} (${result.risk.score}/${result.risk.maxScore})`,
    );
    lines.push("");
    lines.push("| Factor | Score | Detail |");
    lines.push("|---|---|---|");
    for (const f of result.risk.factors) {
      lines.push(`| ${f.name} | ${f.score}/${f.maxScore} | ${f.detail} |`);
    }
    lines.push("");
  }

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Total issues | ${result.totalIssues} |`);
  lines.push(`| Reviewed (AI) | ${result.reviewedIssues} |`);
  lines.push(
    `| Framework | ${result.framework ?? "not detected"} |`,
  );
  lines.push("");

  // Complexity
  if (result.complexity && result.complexity.hotspots.length > 0) {
    lines.push("## 🧠 Complexity Hotspots");
    lines.push("");
    lines.push("| File | Complexity | Cognitive |");
    lines.push("|---|---|---|");
    for (const h of result.complexity.hotspots.slice(0, 5)) {
      lines.push(`| ${h.filePath} | ${h.complexity} | ${h.cognitiveComplexity} |`);
    }
    lines.push("");
  }

  // Acceptance criteria
  if (result.acceptanceValidation) {
    const av = result.acceptanceValidation;
    const icon = av.overallPass ? "✅" : "❌";
    lines.push(`## ${icon} JIRA: ${av.jiraKey} - ${av.summary}`);
    lines.push("");
    for (const c of av.criteria) {
      lines.push(`- ${c.met ? "✅" : "❌"} ${c.description}`);
    }
    lines.push("");
  }

  // Issue breakdown
  if (result.comments.length > 0) {
    lines.push("## Issues Reviewed");
    lines.push("");
    lines.push("| File | Line | Rule | Severity |");
    lines.push("|---|---|---|---|");
    for (const c of result.comments) {
      lines.push(
        `| ${c.filePath} | ${c.line} | \`${c.rule}\` | ${c.severity} |`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [ira-review](https://www.npmjs.com/package/ira-review)*");

  return lines.join("\n");
}
